ZeroWaste/Models/ShoppingListIngredient.cs
using System.ComponentModel.DataAnnotations.Schema;

namespace ZeroWaste.Models
{
    public class ShoppingListIngredient
    {
        public int Id { get; set; }
        public double Quantity { get; set; }
        public bool Selected { get; set; }
        public int ShoppingListId { get; set; }
        [ForeignKey(nameof(ShoppingListId))]
        public ShoppingList ShoppingList { get; set; }

        public int IngredientId { get; set; }
        [ForeignKey(nameof(IngredientId))]
        public Ingredient Ingredient { get; set; }

    }
}

ZeroWaste/Controllers/ShoppingListIngredientsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using ZeroWaste.Data.Handlers.ShoppingListIngredients;
using ZeroWaste.Data.Helpers;
using ZeroWaste.Data.Services.ShoppingLists;
using ZeroWaste.Data.ViewModels.ShoppingList;
using ZeroWaste.Models;

namespace ZeroWaste.Controllers;

[Authorize]
public class ShoppingListIngredientsController : Controller
{
    private readonly IShoppingListIngredientsHandler _shoppingListIngredientsHandler;
    public ShoppingListIngredientsController(IShoppingListIngredientsHandler shoppingListIngredientsHandler)
    {
        _shoppingListIngredientsHandler = shoppingListIngredientsHandler;
    }
    public async Task<IActionResult> IngredientsToAdd(int id, string searchString, int ingredientTypeId)
    {
        var item = await _shoppingListIngredientsHandler.GetShoppingListIngredientsVm(id, searchString, ingredientTypeId);
        return View(nameof(IngredientsToAdd), item);
    }
    public async Task<IActionResult> ChangeCategory(int shoppingListId, int ingredientTypeId)
    {
        var item = await _shoppingListIngredientsHandler.GetShoppingListIngredientsVm(shoppingListId, null, ingredientTypeId);
        return View(nameof(IngredientsToAdd), item);
    }
    public async Task<IActionResult> DeleteShoppingListIngredient(int id)
    {
        int shoppingListId = await _shoppingListIngredientsHandler.HandleDeleteIngredientFromShoppingList(id);
        return RedirectToAction( "Edit", "ShoppingLists", new {id = shoppingListId});
    }
    public async Task<IActionResult> AddIngredientToShoppingList(int ingredientId, int shoppingListId, int typeId)
    {
        await _shoppingListIngredientsHandler
            .AddIngredientToShoppingList(ingredientId, shoppingListId);
        return RedirectToAction(nameof(IngredientsToAdd), new {id = shoppingListId, ingredientTypeId = typeId});
    }
    public async Task<IActionResult> DeleteIngredientFromShoppingList(int ingredientId, int shoppingListId, int typeId)
    {
        await _shoppingListIngredientsHandler
            .DeleteIngredientFromShoppingList(ingredientId, shoppingListId);
        return RedirectToAction(nameof(IngredientsToAdd), new {id = shoppingListId, ingredientTypeId = typeId});
    }
    public async Task<IActionResult> EditQuantity(int shoppingListId)
    {
        var model = await _shoppingListIngredientsHandler.GetEditQuantity(shoppingListId);
        return View(nameof(EditQuantity), model);
    }
    [HttpPost]
    public async Task<IActionResult> EditQuantity(EditQuantityVM quantityVm)
    {
        await _shoppingListIngredientsHandler
            .EditQuantityOfNewIngredients(quantityVm);
        return RedirectToAction("Edit","ShoppingLists",new {id = quantityVm.ShoppingListId});
    }
    public async Task<IActionResult> ChangeIngredientSelection(int shoppingListIngredientId)
    {
        int shoppingListId = await _shoppingListIngredientsHandler
                .ChangeShoppingListIngredientSelection(shoppingListIngredientId);
        return RedirectToAction("Edit", "ShoppingLists", new {id = shoppingListId});
    }
}

ZeroWaste/Views/ShoppingListIngredients/EditQuantity.cshtml
@using ZeroWaste.Data.ViewModels.ShoppingList
@model EditQuantityVM
@{
    ViewData["Title"] = "Edycja ilości";
}
<div class="col-md-10 offset-1">
    <div class="row">
        <div class="col-md-4 offset-4 text-center">
            <h3>Edycja ilości</h3>
        </div>
    </div>
    <br/>
    <div class="row">
        <div class="col-md-8 offset-2">
            <form asp-controller="ShoppingListIngredients" asp-action="EditQuantity" id="test1">
                @for (int i = 0; i < @Model.IngredientsToEditQuantity.Count(); i++)
                {
                    <div class="row">
                        <div class="col-md-4">
                            <h5>@Model.IngredientsToEditQuantity[i].Ingredient.Name</h5>
                        </div>
                        <div class="col-md-4">
                            <input type="number" class="form-control" asp-for="IngredientsToEditQuantity[i].Quantity" id=@i/>
                        </div>
                        <div class="col-md-4">
                            @Model.IngredientsToEditQuantity[i].Ingredient.UnitOfMeasure.Name
                        </div>
                    </div>
                    <hr/>
                    <input type="number" asp-for="@Model.IngredientsToEditQuantity[i].Id" style="visibility: hidden" value="@Model.IngredientsToEditQuantity[i].Id"/>
                }
                <div class="row">
                    <div class="col-md-9">
                        <input type="number" asp-for="@Model.ShoppingListId" style="visibility: hidden" value="@Model.ShoppingListId"/>
                    </div>
                    <div class="col-md-3">
                        <input type="submit" class="btn btn-dark" value="Zatwierdź"/>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

ZeroWaste/Views/ShoppingListIngredients/IngredientsToAdd.cshtml
@using ZeroWaste.Data.ViewModels.ShoppingList;
@model ShoppingListIngredientsVm;

@{
    ViewData["Title"] = "Lista składników";
}
<div class="row">
    <div class="col-md-4 offset-2">
        <h3>Produkty do dodania</h3>
    </div>
    <div class="col-md-4">
        <form asp-controller="ShoppingListIngredients" asp-action="IngredientsToAdd">
            <div class="row">
                <div class="col-md-10">
                    <input name="searchString" type="text" class="form-control" placeholder="Szukaj składnika..." aria-label="Recipient's username" aria-describedby="button-addon2">
                    <input name="id" type="number" class="form-control" style="visibility: hidden" value="@Model.ShoppingListId">
                    <input name="ingredientTypeId" type="number" class="form-control" style="visibility: hidden" value="@Model.SelectedCategoryId">
                </div>
                <div class="col-md-2">
                    <button class="btn btn-outline-success my-2 my-sm-0" type="submit"><i class="bi bi-search"></i></button>
                </div>
            </div>
        </form>
    </div>
</div>
<br/>
<div class="row">
    <div class="col-md-2">
        <div class="row">
            <div class="col-md-7 offset-2">
                @if (@Model.SelectedCategoryId == 0)
                {
                    <a class="btn btn-oxford-blue text-antique-white btn-oxford-border width-max" asp-action="ChangeCategory" asp-route-ingredientTypeId="0" asp-route-shoppingListId="@Model.ShoppingListId">Wszystkie</a>
                }
                else
                {
                    <a class="btn btn-antique-white text-oxford-blue btn-oxford-border width-max" asp-action="ChangeCategory" asp-route-ingredientTypeId="0" asp-route-shoppingListId="@Model.ShoppingListId">Wszystkie</a>    
                }
                @foreach (var category in @Model.IngredientTypes)
                {
                    @if (category.Id != @Model.SelectedCategoryId)
                    {
                        <a class="btn btn-antique-white text-oxford-blue btn-oxford-border width-max" asp-action="ChangeCategory" asp-route-ingredientTypeId="@category.Id" asp-route-shoppingListId="@Model.ShoppingListId">@category.Name</a>
                    }
                    else
                    {
                        <a class="btn btn-oxford-blue text-antique-white btn-oxford-border width-max">@category.Name</a>
                    }
                }
            </div>
        </div>
    </div>
    <div class="col-md-10">
        <div class="row">
            <div class="col-md-5">
            <p class="h4">Składniki</p>
            <table class="table">
                <thead>
                <tr>
                    <th>Nazwa</th>
                    <th>Jednostka</th>
                    <th></th>
                </tr>
                </thead>
                <tbody>
                @foreach (var item in Model.Ingredients)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Name)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.UnitOfMeasure.Shortcut)
                        </td>
                        <td class="align-middle">
                            <a class="btn-default" asp-action="AddIngredientToShoppingList" asp-route-ingredientId="@item.Id" asp-route-shoppingListId="@Model.ShoppingListId" asp-route-typeId="@Model.SelectedCategoryId"><i class="bi bi-box-arrow-right"></i></a>
                        </td>
                    </tr>
                }
                </tbody>
            </table>
        </div>
            <div class="col-md-5 offset-1">
                <p class="h4">Składniki dodane</p>
                <table class="table">
                    <thead>
                    <tr>
                        <th>Nazwa</th>
                        <th>Jednostka</th>
                        <th></th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach (var item in Model.IngredientsToAddVm.Where(x => x.IsAdded))
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.Name)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.UnitOfMeasure.Shortcut)
                            </td>
                            <td class="align-middle">
                                <a class="btn-default" asp-action="DeleteIngredientFromShoppingList" asp-route-ingredientId="@item.Id" asp-route-shoppingListId="@Model.ShoppingListId" asp-route-typeId="@Model.SelectedCategoryId"><i class="bi bi-box-arrow-left"></i></a>
                            </td>
                        </tr>
                    }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
@await Html.PartialAsync("_ShoppingListIngredientsConfirmButton", @Model);

ZeroWaste/Views/ShoppingListIngredients/NewIngredientForShoppingList.cshtml
@using ZeroWaste.Data.ViewModels.ShoppingList;
@model ShoppingListIngredientsVm;

@{
    ViewData["Title"] = "Lista składników";
}
<div class="row">
    <div class="col-md-4 offset-2">
        <h3>Produkty do dodania</h3>
    </div>
    <div class="col-md-4">
        <form asp-controller="ShoppingListIngredients" asp-action="NewIngredientForShoppingList">
            <div class="row">
                <div class="col-md-10">
                    <input name="searchString" type="text" class="form-control" placeholder="Szukaj składnika..." aria-label="Recipient's username" aria-describedby="button-addon2">
                    <input name="id" type="number" class="form-control" style="visibility: hidden" value="@Model.ShoppingListId">
                </div>
                <div class="col-md-2">
                    <button class="btn btn-outline-success my-2 my-sm-0" type="submit"><i class="bi bi-search"></i></button>
                </div>
            </div>
        </form>
    </div>
</div>
<br/>
<div class="col-md-8 offset-md-2">
    <table class="table">
        <thead>
        <tr>
            <th>Nazwa</th>
            <th>Jednostka</th>
            <th>Typ</th>
            <th></th>
        </tr>
        </thead>
        <tbody>
        @foreach (var item in Model.IngredientsToAddVm)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.UnitOfMeasure.Shortcut)
                </td>
                <td>
                   @Html.DisplayFor(modelItem => item.IngredientType.Name)
                </td>
                <td class="align-middle">
                    @if (!(item.IsAdded))
                    {
                        <a class="btn btn-antique-white text-oxford-blue" asp-action="AddIngredientToShoppingList" asp-route-id="@item.Id" asp-route-shoppingListId="@Model.ShoppingListId">Dodaj</a>
                    }
                </td>
            </tr>
        }
        </tbody>
    </table>
</div>
@await Html.PartialAsync("_ShoppingListIngredientsConfirmButton", @Model);