ZeroWaste/Models/HarmfulIngredient.cs
using System.ComponentModel.DataAnnotations.Schema;

namespace ZeroWaste.Models
{
    public class HarmfulIngredient
    {
        public int Id { get; set; }

        public int IngredientId { get; set; }
        [ForeignKey(nameof(IngredientId))]
        public Ingredient Ingredient { get; set; }

        public string UserId { get; set; }
        [ForeignKey(nameof(UserId))]
        public ApplicationUser ApplicationUser { get; set; }
    }
}

ZeroWaste/Controllers/HarmfulIngredientsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using ZeroWaste.Data.Services.HarmfulIngredients;

namespace ZeroWaste.Controllers
{
    [Authorize]
    public class HarmfulIngredientsController : Controller
    {
        private readonly IHarmfulIngredientsService _harmfulIngredientsService;
        public HarmfulIngredientsController(IHarmfulIngredientsService harmfulIngredientsService)
        {
            _harmfulIngredientsService = harmfulIngredientsService;
        }

        public async Task<IActionResult> Index()
        {
            string userId = User.FindFirst(ClaimTypes.NameIdentifier).Value;
            var safeIngredients = await _harmfulIngredientsService.GetSafeIngredientsForUser(userId);
            var harmfulIngredients = await _harmfulIngredientsService.GetHarmfulIngredientsForUser(userId);
            ViewBag.SafeIngredients = safeIngredients;
            ViewBag.HarmfulIngredients = harmfulIngredients;
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> MarkAsHarmful(int ingredientId)
        {
            string userId = User.FindFirst(ClaimTypes.NameIdentifier).Value;
            await _harmfulIngredientsService.MarkIngredientAsHarmful(userId, ingredientId);
            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        public async Task<IActionResult> UnmarkAsHarmful(int ingredientId)
        {
            string userId = User.FindFirst(ClaimTypes.NameIdentifier).Value;
            await _harmfulIngredientsService.UnmarkIngredientAsHarmful(userId, ingredientId);
            return RedirectToAction(nameof(Index));
        }
    }
}

ZeroWaste/Views/HarmfulIngredients/Index.cshtml
@{
    ViewData["Title"] = "Lista produktów szkodliwych";
}


<div class="row">
    <p class="h1">Twoje listy składników</p>
</div>
<div class="row mt-2rem">
    <div class="col-md-5 offset-1">
        <p class="h3">Nieszkodliwe</p>
    </div>
    <div class="col-md-5 offset-1">
        <p class="h3">Szkodliwe - przepisy z tymi składnikami nie będą wyświetlane</p>
    </div>
</div>
<div class="row">
    <div class="col-md-5 offset-1">
        <table class="table table-hover">
            <thead>
                <tr>
                    <th scope="col">Nazwa</th>
                    <th scope="col">Typ</th>
                    <th scope="col">Oznacz jako szkodliwy</th>
                </tr>
            </thead>
            <tbody class="table-group-divider">
                @foreach (var item in ViewBag.SafeIngredients)
                {
                    <tr>
                        <td>
                            @item.IngredientName
                        </td>
                        <td>
                            @item.IngredientType
                        </td>
                        <td class="align-middle">
                            <form asp-controller="HarmfulIngredients" asp-action="MarkAsHarmful" asp-route-ingredientId="@item.IngredientId">
                                <button type="submit" class="btn btn-default"><i class="bi bi-box-arrow-right"></i></button>
                            </form>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
    <div class="col-md-5 offset-1">
        <table class="table table-hover">
            <thead>
                <tr>
                    <th scope="col">Nazwa</th>
                    <th scope="col">Typ</th>
                    <th scope="col">Oznacz jako bezpieczny</th>
                </tr>
            </thead>
            <tbody class="table-group-divider">
                @foreach (var item in ViewBag.HarmfulIngredients)
                {
                    <tr>
                        <td>
                            @item.IngredientName
                        </td>
                        <td>
                            @item.IngredientType
                        </td>
                        <td class="align-middle">
                            <form asp-controller="HarmfulIngredients" asp-action="UnmarkAsHarmful" asp-route-ingredientId="@item.IngredientId">
                                <button type="submit" class="btn btn-default"><i class="bi bi-box-arrow-left"></i></button>
                            </form>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>
<div class="row">
    <div class="col-md-8 offset-2">
        <a asp-action="Index" asp-controller="Home" class="btn btn-default btn-pale-pink float-left">Powrót</a>
    </div>
</div>