ZeroWaste/Controllers/SearchRecipesController.cs
using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ZeroWaste.Data;
using ZeroWaste.Data.Enums;
using ZeroWaste.Data.Handlers.SearchRecipesHandlers;
using ZeroWaste.Data.Handlers.SearchRecipeStrategy;
using ZeroWaste.Data.Services;
using ZeroWaste.Data.Services.Photo;
using ZeroWaste.Data.Services.RecipeIngredients;
using ZeroWaste.Data.Services.Statuses;
using ZeroWaste.Data.Static;
using ZeroWaste.Data.ViewModels;
using ZeroWaste.Data.ViewModels.RecipeSearch;
using ZeroWaste.Models;
using Controller = Microsoft.AspNetCore.Mvc.Controller;
using JsonResult = Microsoft.AspNetCore.Mvc.JsonResult;

namespace ZeroWaste.Controllers;

public class SearchRecipesController : Controller
{
    private List<SortTypeDisplayVm> _sortTypeDisplayVmList;
    private readonly ICategoryService _categoryService;
    private readonly ISearchRecipeHandler _searchRecipeHandler;
    private readonly IStatusesService _statusesService;
    private readonly ISearchRecipeContext _searchRecipeContext;
    private readonly IRecipeIngredientService _recipeIngredientService;
    private readonly IPhotoService _photoService;
    private readonly AppDbContext _context;
    public SearchRecipesController(AppDbContext context, ICategoryService categoryService, ISearchRecipeHandler searchRecipeHandler, IStatusesService statusesService, ISearchRecipeContext searchRecipeContext, IRecipeIngredientService service, IPhotoService photoService)
    {
        _context = context;
        _photoService = photoService;
        _categoryService = categoryService;
        _statusesService = statusesService;
        _searchRecipeHandler = searchRecipeHandler;
        _searchRecipeContext = searchRecipeContext;
        _sortTypeDisplayVmList = SortTypeSupplementer.SupplementSortTypeVm();
        _recipeIngredientService = service;
    }
    public IActionResult Index()
    {
        return View();
    }

    public async Task<IActionResult> SupriseMeResult()
    {
        string userId = null;
        if (User.FindFirst(ClaimTypes.NameIdentifier) != null)
        {
            userId = User.FindFirst(ClaimTypes.NameIdentifier).Value;
        }
        int recipeId = await _searchRecipeHandler.GetRandomRecipeId(userId);
        return RedirectToAction("Details", "Recipes", new {id = recipeId});
    }
    public async Task<IActionResult> SearchByIngredientsAsync()
    {
        string userId = null;
        if (User.FindFirst(ClaimTypes.NameIdentifier) != null)
        {
            userId = User.FindFirst(ClaimTypes.NameIdentifier).Value;
        }
        var recipeIngredientsDropdownsData = await _recipeIngredientService.GetDropdownIngredientsAsync(userId);
        ViewBag.Ingredients = recipeIngredientsDropdownsData.ToList();
        return View(new SearchByIngredientsVm());
    }
    [HttpPost]
    public async Task<IActionResult> AddIngredientAsync(SearchByIngredientsVm searchByIngredientsVm)
    {
        string userId = null;
        if (User.FindFirst(ClaimTypes.NameIdentifier) != null)
        {
            userId = User.FindFirst(ClaimTypes.NameIdentifier).Value;
        }
        var recipeIngredientsDropdownsData = await _recipeIngredientService.GetDropdownIngredientsAsync(userId);
        ViewBag.Ingredients = recipeIngredientsDropdownsData.ToList();
        if (!(ModelState.IsValid))
        {
            return View("SearchByIngredients", searchByIngredientsVm);
        }
        var newSearchByIngredientsVm = _searchRecipeHandler.AddIngredient(searchByIngredientsVm);
        return View("SearchByIngredients", newSearchByIngredientsVm);
    }

    [HttpPost]
    public async Task<IActionResult> DeleteIngredient(SearchByIngredientsVm searchByIngredientsVm)
    {
        string userId = null;
        if (User.FindFirst(ClaimTypes.NameIdentifier) != null)
        {
            userId = User.FindFirst(ClaimTypes.NameIdentifier).Value;
        }
        var recipeIngredientsDropdownsData = await _recipeIngredientService.GetDropdownIngredientsAsync(userId);
        ViewBag.Ingredients = recipeIngredientsDropdownsData.ToList();
        var searchByIngredientsResult = _searchRecipeHandler.DeleteIngredient(searchByIngredientsVm);
        ModelState.Clear();
        return View("SearchByIngredients", searchByIngredientsResult);
    }
    [Microsoft.AspNetCore.Mvc.HttpGet]
    public async Task<JsonResult> SearchByIngredientsAuto()
    {
        string term = HttpContext.Request.Query["term"].ToString();
        var list = await _context.Ingredients.Where( x=> x.Name.StartsWith(term)).Select(x => x.Name).ToListAsync();
        return Json(list);
    }    
    public async Task<IActionResult> SearchByCategories()
    {
        List<Category> categories = await _categoryService.GetAllAsync();
        var tmp = await _searchRecipeHandler.GetCategoriesSearchVm();
        return View(tmp);
    }
    public async Task<IActionResult> SearchByCategoryResult(int categoryId)
    {
        //ViewBag.SortTypes = Enum.GetValues(typeof(SortTypes)).Cast<SortTypes>().ToList();
        ViewBag.SortTypes = _sortTypeDisplayVmList;
        ViewBag.PageTitle = "Wyszukiwanie po kategoriach";
        var user = User.FindFirst(ClaimTypes.NameIdentifier);
        string userId = null;
        if (user is not null)
        {
            userId = user.Value;
        }
        var resultVm = await _searchRecipeContext.GetSearchRecipeResultVm(new SearchRecipeResultsVm()
        {
            CategoryId = categoryId,
            SearchType = SearchType.Categories,
            UserId = userId//User.FindFirst(ClaimTypes.NameIdentifier).Value,
        });
        return View("SearchResult", resultVm);
    }
    [HttpPost]
    public async Task<IActionResult> SearchByIngredientsResult(SearchByIngredientsVm searchByIngredientsVm)
    {
        ViewBag.PageTitle = "Wyszukiwanie po składnikach";
        ViewBag.SortTypes = _sortTypeDisplayVmList;
        //ViewBag.SortTypes = Enum.GetValues(typeof(SortTypes)).Cast<SortTypes>().ToList();
        var user = User.FindFirst(ClaimTypes.NameIdentifier);
        string userId = null;
        if (user is not null)
        {
            userId = user.Value;
        }
        SearchRecipeResultsVm searchRecipeResultsVm =
            await _searchRecipeContext.GetSearchRecipeResultVm(new SearchRecipeResultsVm()
            {
                IngredientsLists = searchByIngredientsVm.SingleIngredientToSearchVm,
                SearchType = SearchType.Ingredients,
                UserId = userId
            });
        return View("SearchResult", searchRecipeResultsVm);
    }
    [HttpPost]
    public async Task<IActionResult> SearchRecipesFilteredResult(SearchRecipeResultsVm resultsVm)
    {
        ViewBag.PageTitle = resultsVm.PageTitle;
        ViewBag.SortTypes = _sortTypeDisplayVmList;
        var user = User.FindFirst(ClaimTypes.NameIdentifier);
        string userId = null;
        if (user is not null)
        {
            userId = user.Value;
        }
        if(resultsVm.IngredientsLists != null && resultsVm.SearchType != SearchType.Categories)
        {
            resultsVm.SearchType = SearchType.IngredientsFiltered;
            resultsVm.UserId = userId;
            resultsVm = await _searchRecipeContext.GetSearchRecipeResultVm(resultsVm);
        }
        else
        {
            resultsVm.SearchType = SearchType.Categories;
            resultsVm.UserId = userId;
            resultsVm = await _searchRecipeContext.GetSearchRecipeResultVm(resultsVm);
        }
        return View("SearchResult", resultsVm);
    }

    [HttpPost]
    public async Task<IActionResult> SearchRecipeSentenceResult(SearchRecipeResultsVm resultsVm)
    {
        ViewBag.PageTitle = resultsVm.PageTitle;
        ViewBag.SortTypes = _sortTypeDisplayVmList;
        if (resultsVm.RecipesListBase.IsRecipeResultNullOrEmpty())
            resultsVm.RecipesListBase = resultsVm.RecipesList;
        if (string.IsNullOrEmpty(resultsVm.SearchSentence))
            resultsVm.RecipesList = resultsVm.RecipesListBase;
        else
            resultsVm.RecipesList = resultsVm.RecipesListBase.Where(x =>
                    x.Title.ToLower().Contains(resultsVm.SearchSentence.ToLower()))
                .ToList();
        //
        if (resultsVm != null)
        {
            foreach (var item in resultsVm.RecipesList)
            {
                item.Photo = await _photoService.GetFirstByRecipeAsync(item.Id);
            }
        }
        return View("SearchResult", resultsVm);
    }
    public async Task<IActionResult> SearchRecipesSortedResult(SearchRecipeResultsVm resultsVm)
    {
        ViewBag.PageTitle = resultsVm.PageTitle;
        ViewBag.SortTypes = _sortTypeDisplayVmList;
        var result = await _searchRecipeHandler.GetSearchRecipeResultVmSorted(resultsVm);
        return View("SearchResult", resultsVm);
    }
    [HttpPost]
    public async Task<IActionResult> ReturnToSearchByIngredients(SearchRecipeResultsVm resultsVm)
    {
        string userId = null;
        if (User.FindFirst(ClaimTypes.NameIdentifier) != null)
        {
            userId = User.FindFirst(ClaimTypes.NameIdentifier).Value;
        }
        var recipeIngredientsDropdownsData = await _recipeIngredientService.GetDropdownIngredientsAsync(userId);
        ViewBag.Ingredients = recipeIngredientsDropdownsData.ToList();
        SearchByIngredientsVm searchByIngredientsVm = new()
        {
            SingleIngredientToSearchVm = resultsVm.IngredientsLists
        };
        return View("SearchByIngredients", searchByIngredientsVm);
    }
    [Authorize(Roles = UserRoles.Admin)]
    public async Task<IActionResult> SearchForConfirm(int statusId = 2)
    {
        //ViewBag.SortTypes = Enum.GetValues(typeof(SortTypes)).Cast<SortTypes>().ToList();
        ViewBag.SortTypes = _sortTypeDisplayVmList;
        ViewBag.Statuses = await _statusesService.GetAllAsync();

ZeroWaste/Views/SearchRecipes/Index.cshtml
@{
    ViewData["Title"] = "Wybierz sposób";
}
<div class="col-md-6 offset-3">
    <div class="row">
        <a class="btn btn-platinum text-oxford search-option" asp-controller="SearchRecipes" asp-action="SearchByIngredients">
            Po składnikach
        </a>
    </div>
    <br/>
    <div class="row">
        <a class="btn btn-platinum text-oxford search-option" asp-controller="SearchRecipes" asp-action="SearchByCategories">
            Po kategorii
        </a>
    </div>
    <br/>
    <div class="row">
        <a class="btn btn-platinum text-oxford search-option" asp-controller="SearchRecipes" asp-action="SupriseMeResult">
            Zaskocz mnie
        </a>
    </div>
</div>

ZeroWaste/Views/SearchRecipes/SearchByCategories.cshtml
@using ZeroWaste.Data.ViewModels.CategorySearch;
@model IEnumerable<CategorySearchVm>
@{
    ViewData["Title"] = "Szukaj po kategoriach";
}
<div class="view-search">
    <div class="col-md-6 offset-3">
        <div class="row">
            <div class="text-center">
                <h3>Wyszukaj przepis po kategoriach</h3>
            </div>
        </div>
        <div class="row">
            @foreach (var item in @Model)
            {
                <div class="col-md-3 col-sm-6 mb-3 text-center">
                    <a class="btn" asp-action="SearchByCategoryResult" asp-route-categoryId="@item.Id">
                        <img class="rounded-circle" src="@Url.Content(@item.Image)" style="width:100px; height:100px; object-fit: cover" alt="test"/>
                    </a>
                    <h5>@item.Name</h5>
                </div>
            }
        </div>
    </div>
</div>

ZeroWaste/Views/SearchRecipes/SearchByIngredients.cshtml
@using Newtonsoft.Json
@using ZeroWaste.Data.ViewModels.RecipeIngredients
@using ZeroWaste.Data.ViewModels.RecipeSearch;
@model SearchByIngredientsVm
@{
    ViewData["Title"] = "Szukaj po składnikach";
    var ingredients = ViewBag.Ingredients as IEnumerable<ExistingIngredient>;
    var data = JsonConvert.SerializeObject(ingredients);
}
<div class="view-search">
    <div class="row">
        <div class="col-md-3">
            <p class="h6">1. Wybierz składnik</p>
            <p class="h6">2. Wpisz ilość</p>
            <p class="h6">3. Naciśnij przycisk "+"</p>
        </div>
        <div class="col-md-4 offset-1">
            <div class="row">
                <div class="text-center">
                    <h3>Uzupełnij składniki do wyszukania przepisu</h3>
                </div>
            </div>
            <br/>
            <form asp-action="AddIngredient" asp-controller="SearchRecipes">
                @if (@Model.SingleIngredientToSearchVm != null)
                {
                    @for (int i = 0; i < @Model.SingleIngredientToSearchVm.Count; i++)
                    {
                        @Html.HiddenFor(x => x.SingleIngredientToSearchVm[i].Name)
                        @Html.HiddenFor(x => x.SingleIngredientToSearchVm[i].Quantity)
                        @Html.HiddenFor(x => x.SingleIngredientToSearchVm[i].Unit)
                        @Html.HiddenFor(x => x.SingleIngredientToSearchVm[i].Index)
                    }
                }
                <div class="row">
                    <div class="col-md-4">
                        @*<input type="text" id="nameInput" asp-for="@Model.Name" placeholder="składnik"/>*@
                        @Html.DropDownListFor(x => x.Name, new SelectList(ViewBag.Ingredients, "Name", "Name"), new {@class = "form-select js-example-basic-single"})
                        <span class="text-danger" asp-validation-for="@Model.Name"></span>
                        <span class="text-danger" id="notExistIgnredient" style="visibility: hidden">Brak składnika na liście</span>
                    </div>
                    <div class="col-md-2">
                        <input type="text" class="form-control" id="unitOfMeasure" asp-for="@Model.Unit" tabindex="-1" style="pointer-events: none;"/>
                    </div>
                    <div class="col-md-3">
                        <input type="number" class="form-control" id="quantityInput" asp-for="@Model.Quantity"/>
                        <span class="text-danger" asp-validation-for="@Model.Quantity"></span>
                        <span class="text-danger" id="nanQuantity" style="visibility: hidden">Ilość musi być większa od 1</span>
                    </div>
                    <div class="col-md-2">
                        <button type="submit" class="btn btn-antique-white text-oxford-blue" id="addIngredientBtn">
                            <i class="bi bi-plus"></i>
                        </button>
                    </div>
                </div>
            </form>
            <div class="row">
                <div class="col-md-6 offset-3">
                    <form asp-action="SearchByIngredientsResult">
                        @if (@Model.SingleIngredientToSearchVm != null)
                        {
                            @for (int i = 0; i < @Model.SingleIngredientToSearchVm.Count; i++)
                            {
                                @Html.HiddenFor(x => x.SingleIngredientToSearchVm[i].Name)
                                @Html.HiddenFor(x => x.SingleIngredientToSearchVm[i].Quantity)
                                @Html.HiddenFor(x => x.SingleIngredientToSearchVm[i].Unit)
                                @Html.HiddenFor(x => x.SingleIngredientToSearchVm[i].Index)
                            }
                        }
                        <input type="submit" class="btn btn-umber text-platinum width-max" value="Wyszukaj"/>
                    </form>
                </div>
            </div>
            <br/>
        </div>
        <div class="col-md-6 offset-3">
            <div class="row">
                <div class="text-center">
                    <p>Składniki</p>
                </div>
            </div>
            <div class="row">
                <table>
                    <thead>
                    <tr>
                        <th>#</th>
                        <th>Produkt</th>
                        <th>Ilość</th>
                        <th>Jednostka</th>
                        <th></th>
                    </tr>
                    </thead>
                    <tbody>
                    @if (@Model.SingleIngredientToSearchVm != null)
                    {
                        @foreach (var item in @Model.SingleIngredientToSearchVm)
                        {
                            <tr>
                                <td>@item.Index</td>
                                <td>@item.Name</td>
                                <td>@item.Quantity</td>
                                <td>@item.Unit</td>
                                <td>
                                    <form asp-controller="SearchRecipes" asp-action="DeleteIngredient">
                                        @for (int i = 0; i < @Model.SingleIngredientToSearchVm.Count; i++)
                                        {
                                            @Html.HiddenFor(x => x.SingleIngredientToSearchVm[i].Name)
                                            @Html.HiddenFor(x => x.SingleIngredientToSearchVm[i].Unit)
                                            @Html.HiddenFor(x => x.SingleIngredientToSearchVm[i].Index)
                                            <input type="hidden" asp-for="SingleIngredientToSearchVm[i].Quantity" value="@Model.SingleIngredientToSearchVm[i].Quantity"/>
                                        }
                                        <input type="hidden" asp-for="Name" value="@item.Name"/>
                                        <button class="btn btn-pale-pink">
                                            <i class="bi bi-trash"></i>
                                        </button>
                                    </form>
                                </td>
                            </tr>
                        }
                    }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
@section Scripts
{
    <script src="https://ajax.aspnetcdn.com/ajax/jQuery/jquery-1.10.0.min.js" type="text/javascript"></script>
    <script src="https://ajax.aspnetcdn.com/ajax/jquery.ui/1.9.2/jquery-ui.min.js" type="text/javascript"></script>
    <link href="https://ajax.aspnetcdn.com/ajax/jquery.ui/1.9.2/themes/blitzer/jquery-ui.css" rel="Stylesheet" type="text/css"/>
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet"/>
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
    <script>
        $(document).ready(function () {
            $('.js-example-basic-single').select2();
        });
    </script>
    <script>
        $("#nameInput").autocomplete({
            source: "/SearchRecipes/SearchByIngredientsAuto"
        });
    </script>
    <script>
        $("#document").ready(function () {
            $("#nameInput").val('');
            $("#quantityInput").val(0);
        })
    </script>
    <script>
        $('#Name').on('change', function () {
            var select = document.getElementById('Name');
            var value = select.options[select.selectedIndex].text;

            var ingredientsJson = JSON.parse(he.decode('@data'));
            var filtered = ingredientsJson.filter(a => a.Name == value);

            if (!filtered[0]) {
                $("#addIngredientBtn").prop('disabled', true);
                $("#notExistIgnredient").css('visibility', 'visible');
                return;
            }

            $("#addIngredientBtn").prop('disabled', false);
            $("#notExistIgnredient").css('visibility', 'hidden');
            var unitOfMeasure = filtered[0]['UnitOfMeasure']['Name'];
            document.getElementById('unitOfMeasure').value = unitOfMeasure;
            $('#unitOfMeasure').val(unitOfMeasure);
        });
    </script>
    @*<script>
        $('#quantityInput').on('change', function (){
            var quantityInputVal = $('#quantityInput').val();
            if (!(parseInt(quantityInputVal))){
                $('#quantityInput').val(0);
                $("#nanQuantity").css('visibility', 'visible');
            }
            else{
                $("#nanQuantity").css('visibility', 'hidden');
            }
        });
    </script>
    @*<script>
        $("#nameInput").focusout(function (){
            var _url = '/SearchRecipes/SearchByIngredientsAuto';
            var ingredientsList = [];
            $.ajax({
                url: _url,
                type: "GET",
                dataType:"json",
                success: function(data){
                    data = data.map(function(x) {
                      return x.toLowerCase()
                    })
                    var tmp = jQuery.inArray($("#nameInput").val().toLowerCase(), data);
                    if (tmp === -1){
                        $("#addIngredientBtn").prop('disabled', true);
                        $("#notExistIgnredient").css('visibility', 'visible');
                    }
                    else{
                        $("#addIngredientBtn").prop('disabled', false);
                        $("#notExistIgnredient").css('visibility', 'hidden');
                    }
                }
            });
            })
    </script>*@
}