ZeroWaste/Models/ShoppingList.cs
using System.ComponentModel.DataAnnotations.Schema;

namespace ZeroWaste.Models
{
    public class ShoppingList
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Note { get; set; }
        public DateTime CreatedAt { get; set; }

        public string UserId { get; set; }
        [ForeignKey(nameof(UserId))]
        public ApplicationUser ApplicationUser { get; set; }

        public List<ShoppingListIngredient> ShoppingListIngredients { get; set; }
    }
}

ZeroWaste/Controllers/ShoppingListsController.cs
using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using ZeroWaste.Data.Handlers.ShoppingListHandlers;
using ZeroWaste.Data.Services.ShoppingLists;
using ZeroWaste.Data.ViewModels.ShoppingList;
using ZeroWaste.Models;

namespace ZeroWaste.Controllers;

[Authorize]
public class ShoppingListsController : Controller
{
    private readonly IShoppingListsService _shoppingListsService;
    private readonly IShoppingListHandler _shoppingListHandler;
    public ShoppingListsController(IShoppingListsService shoppingListsService, IShoppingListHandler shoppingListHandler)
    {
        _shoppingListsService = shoppingListsService;
        _shoppingListHandler = shoppingListHandler;
    }
    public async Task<IActionResult> Index()
    {
        List<ShoppingList> shoppingLists = await _shoppingListHandler
            .GetShoppingListsByUserId(GetLoggedUser());
        var tmp = User.FindFirst(ClaimTypes.NameIdentifier);
        return View(nameof(Index), shoppingLists);
    }
    public async Task<IActionResult> Edit(int id)
    {
        ViewBag.Hidden = "hidden";
        var shoppingList = await _shoppingListHandler
            .GetShoppingListById(id);
        if (shoppingList is null)
        {
            Response.StatusCode = 404;
            return View("NotFound");
        }
        return View(nameof(Edit),shoppingList);
    }
    public async Task<IActionResult> Delete(int id)
    {
        if (!await _shoppingListHandler.IsShoppingListExists(id))
        {
            Response.StatusCode = 404;
            return View("NotFound");
        }
        await _shoppingListHandler.DeleteAsync(id);
        return RedirectToAction(nameof(Index));
    }
    public IActionResult ConfirmShoppingList(int id)
    {
        return RedirectToAction(nameof(Index));
    }
    public IActionResult Create()
    {
        return View();
    }
    [HttpPost]
    public async Task<IActionResult> Create(NewShoppingListVM shoppingListVm)
    {
        if (!ModelState.IsValid)
            return View("Create", shoppingListVm);
        var addedShoppingList = await _shoppingListHandler.Create(shoppingListVm, User.FindFirst(ClaimTypes.NameIdentifier).Value);
        return RedirectToAction("IngredientsToAdd", "ShoppingListIngredients", new {id = addedShoppingList.Id});
    }
    [HttpPost]
    public async Task<IActionResult> EditTitle(ShoppingList shoppingList)
    {
        var tmp = await _shoppingListsService.IsShoppingListExists(shoppingList.Id);
        if (!(tmp))
            return View("NotFound");
        await _shoppingListsService.EditAsync(shoppingList);
        return RedirectToAction("Edit", new {id = shoppingList.Id});
    }

    private string GetLoggedUser()
    {
        var user = User.FindFirst(ClaimTypes.NameIdentifier);
        if (user is null)
            throw new Exception("There is no logged user");
        return user.Value;
    }
}

ZeroWaste/Views/ShoppingLists/AddIngredientToShoppingList.cshtml
@using ZeroWaste.Data.ViewModels.ShoppingList;
@model ShoppingListIngredientsVM;

@{
    ViewData["Title"] = "Lista składników";
}
<div class="col-md-10 offset-1">
    <div class="row">
        <div class="col-md-8">
            <h3>Produkty</h3>
        </div>
        <div class="col-md-4">
            <form asp-controller="Ingredients" asp-action="Index">
                <div class="row">
                    <div class="col-md-10">
                        <input name="searchString" type="text" class="form-control" placeholder="Szukaj składnika..." aria-label="Recipient's username" aria-describedby="button-addon2">
                    </div>
                    <div class="col-md-2">
                        <button class="btn btn-outline-success my-2 my-sm-0" type="submit"><i class="bi bi-search"></i></button>
                    </div>
                </div>
            </form>
        </div>
    </div>
    <br/>
    <div class="col-md-8 offset-md-2">
        <table class="table">
            <thead>
                <tr>
                    <th></th>
                    <th></th>
                    <th></th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
            @foreach (var item in Model.IngredientShoppingListVms)
            {
                <tr>
                    <td >
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td >
                        @Html.DisplayFor(modelItem => item.UnitOfMeasure.Shortcut)
                    </td>
                    <td >
                        @Html.DisplayFor(modelItem => item.IngredientType.Name)
                    </td>
                    <td class="align-middle">
                        <a class="btn btn-add">Dodaj</a>
                    </td>
                </tr>
            }
            </tbody>
        </table>
    </div>
</div>

ZeroWaste/Views/ShoppingLists/Create.cshtml
@using ZeroWaste.Data.ViewModels.ShoppingList
@model NewShoppingListVM
@{
    ViewData["Title"] = "Dodaj listę";
}
<div class="col-md-10 offset-1">
    <div class="row">
        <div class="col-md-4 offset-4 text-center">
            <h3>Nowa lista zakupów</h3>
        </div>
    </div>
    <hr/>
    <div class="row">
        <div class="col-md-6 offset-3">
            <form asp-controller="ShoppingLists" asp-action="Create">
                <div class="form-group text-center">
                    <label asp-for="Title" class="control-label"></label>
                    <input asp-for="Title" class="form-control"/>
                    <span asp-validation-for="Title" class="text-danger"></span>
                </div>
                <br/>
                <div class="form-group text-center">
                    <label asp-for="Note" class="control-label"></label>
                    <input asp-for="Note" class="form-control"/>
                    <span asp-validation-for="Note" class="text-danger"></span>
                </div>
                <br/>
                <div class="form-group">
                    <input type="submit" value="Zapisz" class="btn btn-antique-white text-oxford-blue"/>
                </div>
            </form>
        </div>
    </div>
</div>

ZeroWaste/Views/ShoppingLists/Edit.cshtml
@using ZeroWaste.Models;
@model ShoppingList
@{
    ViewData["Title"] = "Shopping list";
}
<div class="col-md-10 offset-1">
    <div class="row">
        <div class="col-md-8">
            <h3>Lista zakupów: @Model.Title (@Model.ShoppingListIngredients.Count)</h3>
        </div>
    </div>
    <div class="row">
        <div class="col-md-10">
            <p>Notatka: @Model.Note</p>
        </div>
        <div class="col-md-2">
            <button id="btnEditTitleShow" style="background: transparent" data-toggle="tooltip" data-placement="bottom" title="Edytuj tytuł">
                <i class="bi bi-pencil-square"></i>
            </button>
        </div>
    </div>
    <div class="row">
        <div class="col-md-8">
            <div>
                <div id="partialEditTitleSection" style="visibility:hidden">
                    @await Html.PartialAsync("_ShoppingListEditTitle", Model)
                </div>
            </div>
        </div>
    </div>
    <br/>
    @foreach (var item in @Model.ShoppingListIngredients.OrderBy(x => x.Ingredient.Name))
    {
        <div class="row">
            <div class="col-md-12">
                <div class="card shopping-list-edit">
                    <div class="row">
                        <div class="col-md-6">
                            <div class="row">
                                <div class="col-md-1">
                                    @if (!(item.Selected))
                                    {
                                        <a class="btn btn-white width-max height-max" asp-controller="ShoppingListIngredients" asp-action="ChangeIngredientSelection" asp-route-shoppingListIngredientId="@item.Id">
                                            <i class="bi bi-square"></i>
                                        </a>
                                    }
                                    else
                                    {
                                        <a class="btn btn-white width-max height-max" asp-controller="ShoppingListIngredients" asp-action="ChangeIngredientSelection" asp-route-shoppingListIngredientId="@item.Id">
                                            <i class="bi bi-check-square"></i>
                                        </a>
                                    }
                                </div>
                                <div class="col-md-11">
                                    <h5>@item.Ingredient.Name</h5>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-2 d-flex align-items-center justify-content-center">
                            <div>
                                <h5>@item.Quantity</h5>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="col-md-4 offset-4">
                                <a class="btn btn-oxford-blue text-platinum height-max width-max" asp-controller="ShoppingListIngredients" asp-action="DeleteShoppingListIngredient" asp-route-id="@item.Id" data-toggle="tooltip" data-placement="bottom" title="Usuń">
                                    <i class="bi bi-trash"></i>
                                </a>
                            </div>    
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <br/>
    }
    @await Html.PartialAsync("_CreateShoppingListItemButton")
</div>
@section Scripts
{
    <script>
    $("#btnEditTitleShow").click(function (){
       if($("#partialEditTitleSection").css("visibility") === "hidden"){
            $("#partialEditTitleSection ").css("visibility", "visible") 
       }
       else{
           $("#partialEditTitleSection").css("visibility", "hidden")
       }
    })
    </script>
    <script>
        $(function () {
            $('[data-toggle="tooltip"]').tooltip()
        })
    </script>
}

ZeroWaste/Views/ShoppingLists/Index.cshtml
@using ZeroWaste.Models;
@model List<ShoppingList>
@{
    ViewData["Title"] = "Shopping Lists";
}
<div class="col-md-10 offset-1">
    <div class="row">
        <div class="col-md-5">
            <h3>Listy zakupów</h3>
            <br/>
        </div>
    </div>
    @foreach (var item in Model)
    {
        <div class="row">
            <div class="col-md-12">
                <div class="card shopping-list">
                    <div class="row">
                        <div class="col-md-4 d-flex align-items-center justify-content-center">
                            <div>
                                <h5>@item.Title</h5>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <br/>
                            <p class="card-text">Ilość składników: @item.ShoppingListIngredients.Count()</p>
                            <hr/>
                            <p class="card-text">Notatka: @item.Note</p>
                        </div>
                        <div class="col-md-4">
                            <div class="row">
                                <div class="col-md-6"></div>
                                <div class="col-md-5">
                                    <br/>
                                    <a class="btn btn-pale-pink width-max" asp-controller="ShoppingLists" asp-action="Edit" asp-route-id="@item.Id" data-toggle="tooltip" data-placement="bottom" title="Podgląd">
                                        <i class="bi bi-search"></i>
                                    </a>
                                    <br/>
                                    <br/>
                                    <a class="btn btn-pale-pink width-max" asp-action="Delete" asp-route-id="@item.Id" data-toggle="tooltip" data-placement="bottom" title="Usuń">
                                        <i class="bi bi-trash"></i>
                                    </a>
                                </div>
                                <div class="col-md-1"></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <br/>
    }
</div>
@await Html.PartialAsync("_CreateNewShoppingList")

@section Scripts
{
    <script>
        $(function () {
          $('[data-toggle="tooltip"]').tooltip()
        })
    </script>
}